spring.application.name=tortoise-web
server.port=8080
server.servlet.context-path=/

spring.datasource.host = 192.168.3.11
#spring.datasource.host = localhost
spring.datasource.port = 3306
spring.datasource.database = db_tortoise
spring.datasource.url=jdbc:mysql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.database}?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true

spring.datasource.username=root
spring.datasource.password=usiytvsiid5843
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000

mybatis-plus.mapper-locations=classpath*:mapper/**/*.xml
mybatis-plus.type-aliases-package=io.github.johntortoise.web.model
mybatis-plus.configuration.map-underscore-to-camel-case=true
mybatis-plus.configuration.cache-enabled=false

mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.slf4j.Slf4jImpl

mybatis-plus.global-config.db-config.logic-delete-field=isDeleted
mybatis-plus.global-config.db-config.logic-delete-value=1
mybatis-plus.global-config.db-config.logic-not-delete-value=0
mybatis-plus.configuration.default-executor-type=batch

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.mode=HTML5

spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=Asia/Shanghai
spring.jackson.serialization.write-dates-as-timestamps=false

logging.level.root=INFO
logging.level.io.github.johntortoise=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB


# ==============================
# 导入文件历史存储路径配置
# ==============================
temp.file.path = tmp/excel-import




# ==============================
# 线程池通用配置
# ==============================
thread-pool.common.core-pool-size=5
thread-pool.common.max-pool-size=20
thread-pool.common.queue-capacity=100
thread-pool.common.keep-alive-seconds=60
thread-pool.common.await-termination-seconds=60

thread-pool.after-chat.core-pool-size=5
thread-pool.after-chat.max-pool-size=20
thread-pool.after-chat.queue-capacity=100
thread-pool.after-chat.keep-alive-seconds=60
thread-pool.after-chat.await-termination-seconds=60
thread-pool.after-chat.thread-name-prefix=Async-Service-

thread-pool.import-conversation.core-pool-size=5
thread-pool.import-conversation.max-pool-size=20
thread-pool.import-conversation.queue-capacity=100
thread-pool.import-conversation.keep-alive-seconds=60
thread-pool.import-conversation.await-termination-seconds=60
thread-pool.import-conversation.thread-name-prefix=ImportExcel-

thread-pool.batch-refresh-memory.core-pool-size=5
thread-pool.batch-refresh-memory.max-pool-size=20
thread-pool.batch-refresh-memory.queue-capacity=100
thread-pool.batch-refresh-memory.keep-alive-seconds=60
thread-pool.batch-refresh-memory.await-termination-seconds=60
thread-pool.batch-refresh-memory.thread-name-prefix=BatchRefreshMemoryExecutor-
